name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: clean cache
        run: npm cache clean --force
      - run: npm install -g surge
      - run: npm install
      - run: npm run build
      - run: cd ./build && surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            New version published to Website 
            - Website [link][1]
            [1]: https://www.voting-app.parthmakadiya.in
