name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Install node v14
      - name: Install node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Install surge and dependencies
      - run: npm install -g surge
      - run: npm install

      # Run tests
      - run: npm run test --coverage --watchAll=true
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000

      # create production build
      - run: npm run build

      # deploy it to surge
      - run: cd ./build && cp index.html 200.html && surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}

      # comment on commit
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            New version published to Website 
            - Website [link][1]
            [1]: http://votingapp.surge.sh/
